report-rocrate-filename: "poisson-equation-workflow-run"
report-rocrate-run-name: "Poisson equation"
report-rocrate-run-license: "MIT"
report-rocrate-main-tool: "gmsh"
report-rocrate-validation-severity: "REQUIRED"
report-rocrate-agent-orcid: "https://orcid.org/0009-0008-6162-8404"
report-rocrate-agent-name: "Mahdi Jafarkhani"
report-rocrate-organization-ror: "https://ror.org/04vnq7t77"
report-rocrate-organization-name: "University of Stuttgart"
report-rocrate-organization-url: "https://www.uni-stuttgart.de/en/"
